# docker-compose.yml
version: "3.8"

services:
  web:
    build: .
    container_name: bhangra-detector
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app     # mount code for live edits
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
