version: "3.8"

services:
  backend:
    build: ./backend
    container_name: bhangra-backend
    ports:
      - "8090:8080"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bhangra-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
