services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8081:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py
